language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: script
  env:
    REACT_APP_GITHUB_API_KEY: ${{ secrets.REACT_APP_GITHUB_API_KEY }}
    REACT_APP_FORMIK_ENDPOINT: ${{ secrets.REACT_APP_FORMIK_ENDPOINT }}
    REACT_APP_RECAPTCHA_KEY: ${{ secrets.REACT_APP_RECAPTCHA_KEY }}
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: develop