name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build
        env:
          GATSBY_GITHUB_API_KEY: ${{ secrets.GATSBY_GITHUB_API_KEY }}
          GATSBY_FORMIK_ENDPOINT: ${{ secrets.GATSBY_FORMIK_ENDPOINT }}
          GOOGLE_RECAPTCHA_KEY: ${{ secrets.GOOGLE_RECAPTCHA_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GATSBY_GITHUB_API_KEY }}
          BRANCH: master
          FOLDER: public